import os
import subprocess
import json
from datetime import datetime
from typing import Optional, List
from mcp.server.fastmcp import FastMCP
from dotenv import load_dotenv
from google import genai

# Load project environment (API keys)
load_dotenv()

# Initialize FastMCP server
mcp = FastMCP("Aegis Forensic Sentinel")

# Configuration
AEGIS_BINARY = os.environ.get("AEGIS_BINARY_PATH", "./aegis.exe")
AUDIT_LEDGER = "aegis.audit.jsonl"
DRAFT_DIR = "draft_tickets"

@mcp.tool()
def run_aegis_scan(target_path: str, framework_profile: str = "53") -> str:
    """
    Executes a high-performance Aegis forensic scan on a target file or directory.
    
    Args:
        target_path: The absolute path to the log file or directory to scan.
        framework_profile: The compliance framework to use ("53" for NIST 800-53, "171" for NIST 800-171).
    """
    if framework_profile not in ["53", "171", "100-1"]:
        return "Error: Invalid framework profile. Use '53', '171', or '100-1'."

    try:
        # Construct command
        # --report: Generate compliance artifacts
        # --reset: Ensure a clean state for the forensic window
        command = [AEGIS_BINARY, target_path, "--profile", framework_profile, "--report", "--reset"]
        
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=False
        )
        
        if result.returncode != 0:
            return f"Aegis Execution Failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
            
        return f"Aegis Scan Complete.\nSTDOUT:\n{result.stdout}"

    except Exception as e:
        return f"Unexpected Error executing Aegis: {str(e)}"

@mcp.tool()
def query_compliance_ledger(severity_filter: str = "All") -> str:
    """
    Queries the Aegis forensic audit ledger for security signals.
    This provides read-only access to the source of truth for forensic analysis.
    
    Args:
        severity_filter: Filter by severity ('Critical', 'High', 'Info', or 'All').
    """
    if not os.path.exists(AUDIT_LEDGER):
        return f"Error: Audit ledger '{AUDIT_LEDGER}' not found. Run a scan first."

    results = []
    try:
        # NIST AI RMF Alignment: Strict Read-Only Mode
        with open(AUDIT_LEDGER, "r") as f:
            for line in f:
                record = json.loads(line)
                severity = record.get("severity", "Info")
                
                if severity_filter == "All" or severity_filter.lower() == severity.lower():
                    # Return a subset of fields to keep context clean for the LLM
                    results.append({
                        "timestamp": record.get("timestamp"),
                        "message": record.get("message"),
                        "severity": severity,
                        "nist_control": record.get("metadata", {}).get("nist_control_id") or "N/A",
                        "original_raw": record.get("raw")
                    })
        
        if not results:
            return f"No records found matching severity-filter: {severity_filter}"
            
        return json.dumps(results, indent=2)

    except Exception as e:
        return f"Error reading ledger: {str(e)}"

@mcp.tool()
def draft_poam_ticket(control_id: str, system_id: str, ai_remediation_advice: str) -> str:
    """
    Drafts a Plan of Action and Milestones (POA&M) ticket based on AI remediation advice.
    This does NOT modify the master forensic record, maintaining Human-In-The-Loop (HITL) integrity.
    
    Args:
        control_id: The NIST Control/Requirement ID (e.g., 'AU-3' or '3.14.3').
        system_id: The identifier for the affected system/host.
        ai_remediation_advice: The detailed technical remediation plan generated by the AI.
    """
    if not os.path.exists(DRAFT_DIR):
        os.makedirs(DRAFT_DIR)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"poam_draft_{control_id.replace('.', '_')}_{timestamp}.json"
    filepath = os.path.join(DRAFT_DIR, filename)

    ticket = {
        "draft_type": "AI_GENERATED_POAM",
        "generated_at": datetime.now().isoformat(),
        "system_id": system_id,
        "control_id": control_id,
        "status": "DRAFT_PENDING_HUMAN_REVIEW",
        "remediation_plan": ai_remediation_advice,
        "nist_ai_rmf_compliance": "HITL_ISOLATED"
    }

    try:
        with open(filepath, "w") as f:
            json.dump(ticket, f, indent=2)
            
        return f"Draft PO&M ticket created successfully: {filepath}\nReview this draft before committing to the master OSCAL PO&M."

    except Exception as e:
        return f"Error saving draft ticket: {str(e)}"

@mcp.tool()
def read_manifest_summary() -> str:
    """Reads the high-level NIST_MANIFEST.md for the AI to summarize for leadership."""
    try:
        # The manifest is generated in the root directory by the Rust binary
        # When running from the aegis_mcp folder, we must look one level up
        manifest_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "NIST_MANIFEST.md")
        
        if not os.path.exists(manifest_path):
            return "Manifest not found. Please run an Aegis scan first."

        with open(manifest_path, "r", encoding="utf-8") as f:
            return f.read()
            
    except Exception as e:
        return f"Error reading manifest: {str(e)}"

@mcp.tool()
def generate_executive_brief() -> str:
    """Uses Gemini-2.5-Flash-Lite to synthesize a boardroom-ready SOC brief from forensic data."""
    # 1. Fail-Safe Key Management
    api_key = os.getenv("GEMINI_API_KEY", os.getenv("GOOGLE_API_KEY"))
    if not api_key:
        return "ERROR: GEMINI_API_KEY not found in environment. Cannot generate executive brief."
    
    client = genai.Client(api_key=api_key)
    
    # 2. Data Ingestion
    manifest = read_manifest_summary()
    if "Manifest not found" in manifest:
        return manifest
        
    # Ingest Critical/High findings for context
    findings = query_compliance_ledger(severity_filter="High")
    
    # 3. Embedded System Prompt (Directive 3)
    prompt = f"""
You are a SOC Commander. Read the provided NIST_MANIFEST.md and the list of critical JSON findings.
Output strictly three sections: BLUF, Active Threats, and Tactical Remediation. Do not output raw JSON.

NIST_MANIFEST.md:
{manifest}

LATEST_HIGH_CRITICAL_FINDINGS:
{findings}
"""

    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash-lite',
            contents=prompt
        )
        report_content = response.text
        
        # 5. File Persistence & Timestamping (Phase 9.1)
        root_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
        brief_path = os.path.join(root_dir, "COMMANDERS_BRIEF.md")
        
        # UTC ISO Timestamp
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        header = f"Report Generated: {timestamp}\n\n"
        
        with open(brief_path, "w", encoding="utf-8") as f:
            f.write(header + report_content)
            
        # 6. Concise Success Confirmation (Directive 3)
        return "SUCCESS: The Commander's Update Brief has been generated by Gemini and saved to disk as COMMANDERS_BRIEF.md. The formal POA&M ticket has also been staged in the draft_tickets/ directory."
        
    except Exception as e:
        return f"Error generating briefing via Gemini: {str(e)}"

@mcp.tool()
def update_aegis_baseline(category: str, item_name: str, justification: str) -> str:
    """
    Programmatically updates the Aegis whitelist configuration.
    
    CRITICAL AI SAFETY INSTRUCTION:
    You MUST NOT execute this tool autonomously. Before calling this tool,
    you MUST explicitly ask the user: "Do you authorize me to add this to the baseline?"
    and you MUST receive a clear "yes" from the user.
    
    Args:
        category: Either 'services' or 'processes'.
        item_name: The exact string to whitelist (e.g., 'GameSDK Service').
        justification: The authorization justification.
    """
    if category not in ["services", "processes"]:
        return "Error: category must be 'services' or 'processes'."
        
    baseline_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "aegis_baseline.json")
    
    try:
        if not os.path.exists(baseline_path):
            data = {"authorized_services": [], "authorized_processes": []}
        else:
            with open(baseline_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                
        key = f"authorized_{category}"
        if key not in data:
            data[key] = []
            
        data[key].append({
            "name": item_name,
            "justification": justification
        })
        
        with open(baseline_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
            
        return f"SUCCESS: {item_name} has been added to the Aegis baseline. Future scans will classify this as NORMAL."
    except Exception as e:
        return f"Error updating baseline: {str(e)}"

if __name__ == "__main__":
    mcp.run()
